"""shadow/faucet.py, `muninn faucet`: the evidence-faucet CDR-capture installer.

The rare compounding value of Muninn is Evidence Mode: a CDR ledger that accrues
real context-decision records so value-per-token can eventually be proven. Before
this command that faucet was unreachable by anyone but the maintainer, the hook
scripts were "coming in Phase 2" and the pipeline was pinned to one laptop.
`muninn faucet` makes the faucet a product: one command detects this install's
assistant and context surfaces, generates real (not placeholder) hook config wired
to the CDR faucet, derives every path from the USER's own environment, and prints
exactly what it did and how to verify it.

  muninn faucet --assistant <claude|cursor|codex> --vault <path> --repo .
  muninn faucet --check        # confirm CDRs are actually being captured here

Auto-detection fills in any flag left off (assistant from surfaces, vault from the
user's home, corpus from the assistant's transcript layout). It writes only under
the ledger dir it reports; it never edits the user's live assistant settings and
never touches the vault. Pure stdlib, deterministic, utf-8, no em dashes.

This module used to share `shadow/init.py`'s name and a `--invite`-argv-peek
dispatch with the customer-onboarding installer. The two commands never shared
any flag or code beyond stdlib imports, so they were split into separate
commands: onboarding stayed `muninn init` (see shadow/init.py), and this,
the evidence faucet, became `muninn faucet`.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import stat
import sys
from typing import Any, Dict, List, Optional, Sequence

_here = pathlib.Path(__file__).parent
if str(_here.parent) not in sys.path:
    sys.path.insert(0, str(_here.parent))

from shadow import capture  # noqa: E402
from shadow import cdr as cdrlib  # noqa: E402
from shadow import context_inventory as inv  # noqa: E402

REPO_ROOT = _here.parent  # the muninn checkout this command runs from


# ── surface + corpus detection (reuses Wave 2a inventory) ──────────────────────

def detect_surfaces(config: capture.CaptureConfig) -> Dict[str, Any]:
    """Detect context surfaces under the repo and vault (Wave 2a coverage map).

    Nothing is scanned/audited here, faucet only INVENTORIES which surfaces are
    present so the summary can name them, exactly as `muninn inventory` classifies.
    """
    roots = []
    for r in (config.repo, config.vault):
        rp = pathlib.Path(r)
        if rp.is_dir() and rp not in roots:
            roots.append(rp)
    surfaces: List[Any] = []
    for root in roots:
        try:
            surfaces.extend(inv.detect_surfaces(root, scanned_paths=set()))
        except Exception:
            continue
    # De-duplicate by (surface_type, pointer).
    seen = set()
    uniq = []
    for s in surfaces:
        key = (s.surface_type, s.pointer)
        if key in seen:
            continue
        seen.add(key)
        uniq.append({"surface_type": s.surface_type, "label": s.label,
                     "pointer": s.pointer})
    uniq.sort(key=lambda d: (d["surface_type"], d["pointer"]))
    return {"count": len(uniq), "surfaces": uniq}


# ── hook config generation (the real, no-longer-Phase-2 artifacts) ─────────────

def _write(path: pathlib.Path, text: str, *, executable: bool = False) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    if executable:
        mode = path.stat().st_mode
        path.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def _hook_wrapper(config: capture.CaptureConfig) -> str:
    """A tiny, self-contained hook wrapper. Derived paths only, no personal paths."""
    return (
        "#!/usr/bin/env bash\n"
        "# GENERATED by `muninn faucet`, the evidence faucet hook wrapper.\n"
        "# Maps a Claude Code hook payload (stdin JSON) to a captured CDR.\n"
        "# Fail-safe: a capture fault exits 0 so it can never break a session.\n"
        "set -uo pipefail\n"
        f'MUNINN_REPO="${{MUNINN_REPO:-{config.repo}}}"\n'
        f'MUNINN_VAULT="${{MUNINN_VAULT:-{config.vault}}}"\n'
        f'MUNINN_LEDGER_DIR="${{MUNINN_LEDGER_DIR:-{config.ledger_dir}}}"\n'
        f'MUNINN_ASSISTANT="${{MUNINN_ASSISTANT:-{config.assistant}}}"\n'
        'export MUNINN_VAULT MUNINN_LEDGER_DIR MUNINN_ASSISTANT\n'
        'PYTHONPATH="$MUNINN_REPO${PYTHONPATH:+:$PYTHONPATH}" \\\n'
        '  "${PYTHON:-python3}" -m shadow.capture --from-hook \\\n'
        f'    --assistant "$MUNINN_ASSISTANT" --vault "$MUNINN_VAULT" \\\n'
        f'    --ledger-dir "$MUNINN_LEDGER_DIR" --privacy {config.privacy_mode} \\\n'
        '  || true\n'
    )


def _claude_settings_fragment(hook_cmd: str) -> str:
    """The Claude Code settings.json hooks block to merge (a Read PostToolUse hook)."""
    block = {
        "hooks": {
            "PostToolUse": [
                {
                    "matcher": "Read",
                    "hooks": [
                        {"type": "command", "command": hook_cmd}
                    ],
                }
            ]
        }
    }
    return json.dumps(block, indent=2) + "\n"


def _env_file(config: capture.CaptureConfig) -> str:
    """The per-user pipeline env file, de-hardcodes ops/muninn_daily.sh.

    Source this (or point MUNINN_ENV at it) and the daily pipeline runs against
    THIS user's repo/vault/corpus. Every value is derived from the user's own
    environment; no maintainer path appears.
    """
    return (
        "# GENERATED by `muninn faucet`, per-user Muninn pipeline paths.\n"
        "# Source this file, or set MUNINN_ENV to its path, before the daily run.\n"
        f'export MUNINN_REPO="{config.repo}"\n'
        f'export MUNINN_VAULT="{config.vault}"\n'
        f'export MUNINN_CORPUS="{config.corpus}"\n'
        f'export MUNINN_LEDGER_DIR="{config.ledger_dir}"\n'
        f'export MUNINN_ASSISTANT="{config.assistant}"\n'
    )


def _install_readme(config: capture.CaptureConfig, hooks_dir: pathlib.Path,
                    hook_wrapper: pathlib.Path, verify_cmd: str) -> str:
    return (
        "# Muninn evidence faucet, generated install\n\n"
        "`muninn faucet` generated the files in this directory. They capture one\n"
        "Context Decision Record per memory-read event your assistant makes, so a\n"
        "CDR ledger accrues while you work. Nothing here was hand-edited; re-run\n"
        "`muninn faucet` to regenerate.\n\n"
        "## What was generated\n\n"
        f"- `{hook_wrapper.name}`, the hook wrapper (maps a hook payload to a CDR).\n"
        "- `claude_settings.hooks.json`, the settings block to wire the hook in\n"
        "  (Claude Code). Merge its `hooks` key into your Claude settings.\n"
        "- `muninn.env`, per-user pipeline paths for the optional daily batch run.\n\n"
        "## Wire the live hook (Claude Code)\n\n"
        "Merge `claude_settings.hooks.json`'s `hooks` block into your Claude Code\n"
        "settings (project `.claude/settings.json` or the user settings). The hook\n"
        "runs on every `Read`; it captures only reads of files under your vault, so\n"
        "ordinary source reads never inflate the ledger.\n\n"
        "## Where CDRs land\n\n"
        f"    {config.cdrs_path}\n\n"
        "## Verify it is working\n\n"
        f"    {verify_cmd}\n"
    )


def generate_hook_config(config: capture.CaptureConfig) -> Dict[str, Any]:
    """Generate the real hook config + pipeline env under the ledger dir.

    Returns a manifest of what was written. Every embedded path is derived from
    the user's environment; no maintainer path is emitted.
    """
    ledger = pathlib.Path(config.ledger_dir)
    hooks_dir = ledger / "hooks"
    wrapper = hooks_dir / "muninn_capture.sh"
    settings = hooks_dir / "claude_settings.hooks.json"
    env_file = ledger / "muninn.env"
    readme = hooks_dir / "INSTALL.md"

    _write(wrapper, _hook_wrapper(config), executable=True)
    _write(settings, _claude_settings_fragment(str(wrapper)))
    _write(env_file, _env_file(config))
    verify_cmd = f"muninn faucet --check --ledger-dir {config.ledger_dir}"
    _write(readme, _install_readme(config, hooks_dir, wrapper, verify_cmd))

    return {
        "hooks_dir":    str(hooks_dir),
        "hook_wrapper": str(wrapper),
        "settings_fragment": str(settings),
        "env_file":     str(env_file),
        "install_readme": str(readme),
    }


# ── verification (`muninn faucet --check`) ──────────────────────────────────────

def verify_install(config: capture.CaptureConfig) -> Dict[str, Any]:
    """Confirm the faucet works for THIS install, two ways:

      1. MACHINERY self-probe: push a synthetic capture event through the faucet
         into a throwaway ledger and assert a schema-valid CDR comes out. This
         proves the capture path is wired correctly on this machine right now,
         even before any real event has fired.
      2. LEDGER accrual: report how many CDRs the configured ledger actually holds
         (total, valid, memory-joined, latest timestamp).

    Returns a report dict; healthy iff the machinery probe produced a valid CDR.
    """
    import tempfile

    # 1. machinery self-probe (isolated ledger; never touches the real one).
    probe_ok = False
    probe_detail = ""
    try:
        with tempfile.TemporaryDirectory() as td:
            probe_cfg = capture.CaptureConfig(
                assistant=config.assistant, repo=config.repo, vault=config.vault,
                corpus=config.corpus, ledger_dir=td,
                cdrs_path=str(pathlib.Path(td) / "cdrs.jsonl"),
                privacy_mode=config.privacy_mode, supported=config.supported)
            event = {
                "session_id": "muninn-faucet-check",
                "turn_id":    "probe",
                "memory_id":  "self-probe-memory",
                "ts":         "1970-01-01T00:00:00Z",
                "source":     "init_check",
                "event_type": "probe",
            }
            res = capture.capture_event(event, probe_cfg)
            probe_ok = bool(res.get("valid") and res.get("written"))
            probe_detail = f"faucet produced a valid CDR ({res.get('cdr_id')})"
    except Exception as e:
        probe_detail = f"faucet probe FAILED: {e}"

    # 2. real-ledger accrual status.
    cdrs = cdrlib.load_cdrs(pathlib.Path(config.cdrs_path))
    valid = sum(1 for c in cdrs if not cdrlib.validate_cdr(c))
    joined = sum(1 for c in cdrs if cdrlib.has_memory_join(c))
    latest = max((str(c.get("timestamp") or "") for c in cdrs), default="")

    return {
        "machinery_ok":  probe_ok,
        "machinery_detail": probe_detail,
        "cdrs_path":     config.cdrs_path,
        "cdrs_total":    len(cdrs),
        "cdrs_valid":    valid,
        "cdrs_memory_joined": joined,
        "latest_timestamp": latest,
        "supported":     config.supported,
        "assistant":     config.assistant,
    }


# ── summary rendering ──────────────────────────────────────────────────────────

def render_summary(config: capture.CaptureConfig, surfaces: Dict[str, Any],
                   manifest: Dict[str, Any], verify_cmd: str) -> str:
    L = ["=" * 64, "  muninn faucet, evidence faucet configured", "=" * 64,
         f"  assistant        : {config.assistant}"
         + ("" if config.supported else "  (surfaces only; live capture not yet "
                                        "supported for this assistant)"),
         f"  repo             : {config.repo}",
         f"  vault            : {config.vault}",
         f"  transcript source: {config.corpus}"
         + ("  [present]" if pathlib.Path(config.corpus).exists()
            else "  [not present yet]"),
         f"  privacy mode     : {config.privacy_mode}",
         "",
         f"  context surfaces detected: {surfaces['count']}"]
    for s in surfaces["surfaces"][:12]:
        L.append(f"    - [{s['label']}] {s['pointer']}")
    if surfaces["count"] > 12:
        L.append(f"    ... and {surfaces['count'] - 12} more")
    L += [
        "",
        f"  hook config      : {manifest['hooks_dir']}",
        f"  settings block   : {manifest['settings_fragment']}",
        f"  pipeline env     : {manifest['env_file']}",
        f"  CDR ledger (out) : {config.cdrs_path}",
        "",
        "  verify with:",
        f"    {verify_cmd}",
        "=" * 64,
    ]
    return "\n".join(L) + "\n"


def render_check(report: Dict[str, Any]) -> str:
    ok = "OK" if report["machinery_ok"] else "FAILED"
    L = ["=" * 64, f"  muninn faucet --check, faucet health: {ok}", "=" * 64,
         f"  assistant        : {report['assistant']}"
         + ("" if report["supported"] else "  (live capture not yet supported)"),
         f"  machinery        : {report['machinery_detail']}",
         f"  CDR ledger       : {report['cdrs_path']}",
         f"  CDRs accrued     : {report['cdrs_total']} "
         f"({report['cdrs_valid']} valid, {report['cdrs_memory_joined']} "
         f"memory-joined)",
         f"  latest CDR       : {report['latest_timestamp'] or '(none yet)'}"]
    if report["cdrs_total"] == 0:
        L.append("  note             : no CDRs captured yet. The machinery is "
                 "ready; they accrue as your assistant reads vault memory with "
                 "the hook installed.")
    L.append("=" * 64)
    return "\n".join(L) + "\n"


# ── CLI ────────────────────────────────────────────────────────────────────────

def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="muninn faucet",
        description="Configure the Muninn evidence faucet: detect this install's "
                    "assistant + context surfaces, generate real capture-hook "
                    "config, and print how to verify it. Writes only under the "
                    "ledger dir; never edits your assistant settings or vault.")
    p.add_argument("--assistant", default=None,
                   choices=sorted(capture.KNOWN_ASSISTANTS),
                   help="claude|cursor|codex (auto-detected from surfaces if omitted)")
    p.add_argument("--vault", default=None, help="memory vault dir (auto-detected)")
    p.add_argument("--repo", default=None, help="repo / working dir (default: cwd)")
    p.add_argument("--corpus", default=None, help="transcript corpus dir (derived)")
    p.add_argument("--ledger-dir", default=None,
                   help="Muninn state dir holding cdrs.jsonl (default: ~/.muninn)")
    p.add_argument("--privacy", default="standard",
                   choices=sorted(capture.PRIVACY_MODES),
                   help="standard stores memory ids; strict hashes them")
    p.add_argument("--check", action="store_true",
                   help="verify CDRs are being captured for this install (no writes "
                        "to the hook config)")
    p.add_argument("--dry-run", action="store_true",
                   help="print what faucet would detect/generate without writing")
    p.add_argument("--json", action="store_true", help="emit the report as JSON")
    return p


def main(argv: Optional[Sequence[str]] = None, stdout=None) -> int:
    args = _build_parser().parse_args(argv)
    out = stdout or sys.stdout

    config = capture.resolve_config(
        assistant=args.assistant, repo=args.repo, vault=args.vault,
        corpus=args.corpus, ledger_dir=args.ledger_dir, privacy_mode=args.privacy)

    if args.check:
        report = verify_install(config)
        if args.json:
            out.write(json.dumps(report, indent=2, sort_keys=True) + "\n")
        else:
            out.write(render_check(report))
        return 0 if report["machinery_ok"] else 1

    surfaces = detect_surfaces(config)
    verify_cmd = f"muninn faucet --check --ledger-dir {config.ledger_dir}"

    if args.dry_run:
        manifest = {
            "hooks_dir": str(pathlib.Path(config.ledger_dir) / "hooks"),
            "hook_wrapper": str(pathlib.Path(config.ledger_dir) / "hooks"
                               / "muninn_capture.sh"),
            "settings_fragment": str(pathlib.Path(config.ledger_dir) / "hooks"
                                    / "claude_settings.hooks.json"),
            "env_file": str(pathlib.Path(config.ledger_dir) / "muninn.env"),
            "install_readme": str(pathlib.Path(config.ledger_dir) / "hooks"
                                 / "INSTALL.md"),
        }
    else:
        manifest = generate_hook_config(config)

    if args.json:
        out.write(json.dumps({"config": config.to_dict(), "surfaces": surfaces,
                              "manifest": manifest, "verify_cmd": verify_cmd,
                              "dry_run": args.dry_run}, indent=2, sort_keys=True)
                  + "\n")
    else:
        out.write(render_summary(config, surfaces, manifest, verify_cmd))
        if args.dry_run:
            out.write("  (dry run: no files were written)\n")
        if not config.supported:
            out.write(f"  NOTE: '{config.assistant}' surfaces are detected and "
                      "configured, but live capture is not yet wired for it. The "
                      "hook config is generated for when support lands; no CDRs "
                      "will accrue from it today.\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
